export type ProfileData = { slug: string; name: string; beat: string; bio: string; photo: string; instagram: string; facebook: string; x: string; linkedin: string };
export const PROFILE_STORAGE_KEY = "pch-news-columnist-profiles";
export const DEFAULT_PROFILES: Record<string, ProfileData> = {
  "evaldo-poeta": { slug: "evaldo-poeta", name: "Evaldo Poeta", beat: "Cultura e opinião", bio: "Escritor e observador das paisagens humanas. No PCH News, transforma cenas do cotidiano em crônicas para lavar os olhos e abrir novas perguntas.", photo: "https://images.unsplash.com/photo-1500648767791-00dcc994a43e?auto=format&fit=crop&w=500&q=85", instagram: "oevaldopoeta", facebook: "evaldo.poeta", x: "@evaldopoeta", linkedin: "evaldo-poeta" },
  "marina-alves": { slug: "marina-alves", name: "Marina Alves", beat: "Saúde e bem-estar", bio: "Jornalista dedicada a histórias de cuidado, prevenção e transformação social que aproximam informação de quem mais precisa.", photo: "https://images.unsplash.com/photo-1551836022-d5d88e9218df?auto=format&fit=crop&w=500&q=85", instagram: "@marinaalves", facebook: "marina.alves", x: "@marinaalves", linkedin: "marina-alves" },
  "vinicius-mororo": { slug: "vinicius-mororo", name: "Vinicius Mororó", beat: "Cidades e esporte", bio: "Editor-chefe do PCH News e repórter apaixonado pelas pessoas, lugares e movimentos que fazem a Região Oeste acontecer.", photo: "https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?auto=format&fit=crop&w=500&q=85", instagram: "@viniciusmororo", facebook: "vinicius.mororo", x: "@viniciusmororo", linkedin: "vinicius-mororo" },
  "laura-nogueira": { slug: "laura-nogueira", name: "Laura Nogueira", beat: "Cultura", bio: "Repórter de cultura, memória e gastronomia. Procura as histórias que ajudam uma cidade a reconhecer sua própria voz.", photo: "https://images.unsplash.com/photo-1494790108377-be9c29b29330?auto=format&fit=crop&w=500&q=85", instagram: "@lauranogueira", facebook: "laura.nogueira", x: "@lauranogueira", linkedin: "laura-nogueira" },
};
export function readProfiles(): Record<string, ProfileData> { if (typeof window === "undefined") return DEFAULT_PROFILES; try { const stored = window.localStorage.getItem(PROFILE_STORAGE_KEY); const profiles = stored ? { ...DEFAULT_PROFILES, ...JSON.parse(stored) } : DEFAULT_PROFILES; if (profiles["evaldo-poeta"] && ["@evaldopoeta", "evaldopoeta"].includes(profiles["evaldo-poeta"].instagram)) profiles["evaldo-poeta"] = { ...profiles["evaldo-poeta"], instagram: "oevaldopoeta" }; return profiles; } catch { return DEFAULT_PROFILES; } }
export function persistProfiles(profiles: Record<string, ProfileData>) { if (typeof window !== "undefined") { window.localStorage.setItem(PROFILE_STORAGE_KEY, JSON.stringify(profiles)); window.dispatchEvent(new CustomEvent("pch-news-data-changed")); } }
export type ReaderComment = { id: string; articleId: string; name: string; text: string; createdAt: string; status: "pending" | "approved" | "rejected"; reply?: string; repliedBy?: string; repliedAt?: string };
export const COMMENTS_STORAGE_KEY = "pch-news-reader-comments";
export function readComments(): ReaderComment[] { if (typeof window === "undefined") return []; try { const raw = window.localStorage.getItem(COMMENTS_STORAGE_KEY); return raw ? JSON.parse(raw) : []; } catch { return []; } }
export function persistComments(comments: ReaderComment[]) { if (typeof window !== "undefined") { window.localStorage.setItem(COMMENTS_STORAGE_KEY, JSON.stringify(comments)); window.dispatchEvent(new CustomEvent("pch-news-data-changed")); } }
export type AdRequest = { id: string; business: string; contact: string; packageName: string; message: string; status: "received" | "reviewing" | "approved"; createdAtMs: number };
export const ADS_STORAGE_KEY = "pch-news-ad-requests";
export function readAdRequests(): AdRequest[] { if (typeof window === "undefined") return []; try { const raw = window.localStorage.getItem(ADS_STORAGE_KEY); return raw ? JSON.parse(raw) : []; } catch { return []; } }
export function persistAdRequests(items: AdRequest[]) { if (typeof window !== "undefined") { window.localStorage.setItem(ADS_STORAGE_KEY, JSON.stringify(items)); window.dispatchEvent(new CustomEvent("pch-news-data-changed")); } }
