export type ProfileData = { slug: string; name: string; beat: string; bio: string; photo: string; instagram: string; facebook: string; x: string; linkedin: string };
export const PROFILE_STORAGE_KEY = "pch-news-columnist-profiles";
export const DEFAULT_PROFILES: Record<string, ProfileData> = {
  "evaldo-poeta": { slug: "evaldo-poeta", name: "Evaldo Poeta", beat: "Colunista PCH News", bio: "Evaldo Poeta é escritor, poeta terapeuta, psicanalista clínico, cronista e criador da Poesia Cognitiva Hipnótica (PCH), além de criador e colunista do PCH News.", photo: "", instagram: "", facebook: "", x: "", linkedin: "" },
};
export function readProfiles(): Record<string, ProfileData> { if (typeof window === "undefined") return DEFAULT_PROFILES; try { const raw = window.localStorage.getItem(PROFILE_STORAGE_KEY); const stored = raw ? JSON.parse(raw) : {}; const evaldo = stored["evaldo-poeta"] ? { ...DEFAULT_PROFILES["evaldo-poeta"], ...stored["evaldo-poeta"] } : DEFAULT_PROFILES["evaldo-poeta"]; return { "evaldo-poeta": evaldo }; } catch { return DEFAULT_PROFILES; } }
export function persistProfiles(profiles: Record<string, ProfileData>) { if (typeof window !== "undefined") { window.localStorage.setItem(PROFILE_STORAGE_KEY, JSON.stringify(profiles)); window.dispatchEvent(new CustomEvent("pch-news-data-changed")); } }
export type ReaderComment = { id: string; articleId: string; name: string; text: string; createdAt: string; status: "pending" | "approved" | "rejected"; reply?: string; repliedBy?: string; repliedAt?: string };
export const COMMENTS_STORAGE_KEY = "pch-news-reader-comments";
export function readComments(): ReaderComment[] { if (typeof window === "undefined") return []; try { const raw = window.localStorage.getItem(COMMENTS_STORAGE_KEY); return raw ? JSON.parse(raw) : []; } catch { return []; } }
export function persistComments(comments: ReaderComment[]) { if (typeof window !== "undefined") { window.localStorage.setItem(COMMENTS_STORAGE_KEY, JSON.stringify(comments)); window.dispatchEvent(new CustomEvent("pch-news-data-changed")); } }
export type AdRequest = { id: string; business: string; contact: string; packageName: string; message: string; status: "received" | "reviewing" | "approved"; createdAtMs: number; contactName?: string | null; email?: string | null; phone?: string | null; city?: string | null; website?: string | null; socials?: string | null; adType?: string | null; budget?: string | null; period?: string | null; consentAtMs?: number | null; source?: string | null };
export const ADS_STORAGE_KEY = "pch-news-ad-requests";
export function readAdRequests(): AdRequest[] { if (typeof window === "undefined") return []; try { const raw = window.localStorage.getItem(ADS_STORAGE_KEY); return raw ? JSON.parse(raw) : []; } catch { return []; } }
export function persistAdRequests(items: AdRequest[]) { if (typeof window !== "undefined") { window.localStorage.setItem(ADS_STORAGE_KEY, JSON.stringify(items)); window.dispatchEvent(new CustomEvent("pch-news-data-changed")); } }
