import { createFileRoute, Link } from "@tanstack/react-router";
import { useState } from "react";
import { AlertTriangle, Check, CheckCircle2, ChevronLeft, Eye, FileCheck2, Info, RotateCcw, Save, SearchCheck, ShieldCheck, X } from "lucide-react";
import { categories, getCategory, getColumnistName } from "@/data/content";
import { articleRepository, useArticles } from "@/lib/newsroom/store";
import { applySuggestion, getReadiness, reviewEngine, summarize, withResolution } from "@/lib/newsroom/review/engine";
import type { AgentProgress, Severity, Suggestion } from "@/lib/newsroom/review/types";
import { auditArticleSeo, effectiveDescription, effectiveSeoTitle, seoScore, suggestKeyword, suggestMetaDescription, suggestSeoTitle } from "@/lib/seo/audit";
import { slugify } from "@/lib/slug";
export const Route=createFileRoute("/admin")({component:AdminPage});
const severityLabel:Record<Severity,string>={alta:"ALTA",media:"MÉDIA",baixa:"BAIXA"};
function AdminPage(){
  const articles=useArticles(); const [selectedId,setSelectedId]=useState("demo-corredores-de-onibus"); const selected=articles.find(a=>a.id===selectedId)||articles[0]; const [draft,setDraft]=useState(selected); const [tab,setTab]=useState<"conteudo"|"revisao"|"seo">("conteudo"); const [running,setRunning]=useState(false); const [progress,setProgress]=useState<Record<string,AgentProgress["state"]>>({}); const [message,setMessage]=useState("");
  if(!selected)return <main className="p-10">Nenhuma matéria.</main>; if(draft.id!==selected.id)setDraft(selected);
  const readiness=getReadiness(draft); const checks=auditArticleSeo(draft); const score=seoScore(checks); const openSuggestions=readiness.open; const reviewAgents=draft.lastReview?.agents||[];
  const update=(patch:Partial<typeof draft>)=>setDraft(d=>({...d,...patch,updatedAt:new Date().toISOString()}));
  const flash=(m:string)=>{setMessage(m);window.setTimeout(()=>setMessage(""),2200)}; const save=()=>{articleRepository.save(draft);flash("Alterações salvas no newsroom.")};
  const runReview=async()=>{setRunning(true);setTab("revisao");setProgress({});const run=await reviewEngine.run(draft,p=>setProgress(c=>({...c,[p.agentId]:p.state})));const next={...draft,lastReview:run,reviewHistory:[summarize(run),...draft.reviewHistory].slice(0,10),updatedAt:new Date().toISOString()};setDraft(next);articleRepository.save(next);setRunning(false)};
  const applyOne=(s:Suggestion)=>{const r=applySuggestion(draft,s);if(!r.ok){flash("A sugestão não foi aplicada porque o trecho mudou.");return}const next=withResolution({...r.article,lastReview:draft.lastReview},[s.id],"aplicada");setDraft({...next,updatedAt:new Date().toISOString()});articleRepository.save(next);flash("Correção aplicada com segurança.")};
  const ignoreOne=(s:Suggestion)=>{const next=withResolution(draft,[s.id],"ignorada");setDraft(next);articleRepository.save(next)};
  const applyAll=()=>{let current=draft;const applied:string[]=[];for(const s of openSuggestions){const r=applySuggestion(current,s);if(r.ok){current=r.article;applied.push(s.id)}}if(current.lastReview&&applied.length)current=withResolution(current,applied,"aplicada");setDraft({...current,updatedAt:new Date().toISOString()});articleRepository.save(current);flash(applied.length+" correções seguras aplicadas.")};
  const createNew=()=>{const a=articleRepository.create({authorSlug:"rafael-munhoz",category:"politica"});setSelectedId(a.id);setDraft(a);setTab("conteudo")};
  return <main className="min-h-screen bg-background"><header className="sticky top-0 z-20 border-b bg-card/95 backdrop-blur"><div className="mx-auto flex max-w-[1500px] items-center justify-between gap-4 px-4 py-3"><div className="flex items-center gap-3"><Link to="/" className="inline-flex items-center gap-1 text-xs text-muted-foreground"><ChevronLeft size={15}/> site</Link><div className="h-6 w-px bg-border"/><span className="font-display text-xl font-black">PCH News</span><span className="hidden rounded-full bg-primary/10 px-2 py-1 text-[10px] font-bold tracking-wider text-primary md:inline">NEWSROOM</span></div><div className="flex items-center gap-2"><button onClick={createNew} className="rounded-md border px-3 py-2 text-xs font-semibold">Nova matéria</button><button onClick={save} className="inline-flex items-center gap-2 rounded-md bg-foreground px-3 py-2 text-xs font-semibold text-background"><Save size={14}/> Salvar</button></div></div></header>
  <div className="mx-auto grid max-w-[1500px] gap-5 px-4 py-5 lg:grid-cols-[280px_1fr]"><aside className="rounded-xl border bg-card p-3"><div className="px-2 pb-3 text-[10px] font-bold tracking-[.18em] text-muted-foreground">MATÉRIAS</div>{articles.slice(0,18).map(a=><button key={a.id} onClick={()=>{setSelectedId(a.id);setDraft(a);setTab("conteudo")}} className={"mb-1 w-full rounded-md p-3 text-left text-xs "+(a.id===draft.id?"bg-foreground text-background":"hover:bg-muted")}><span className="block truncate font-semibold">{a.title||"Sem título"}</span><span className={"mt-1 block text-[10px] "+(a.id===draft.id?"opacity-70":"text-muted-foreground")}>{a.status} · {getColumnistName(a.authorSlug)}</span></button>)}</aside>
  <section><div className="mb-4 flex flex-col gap-4 rounded-xl border bg-card p-5 md:flex-row md:items-start md:justify-between"><div><span className="kicker">EDITOR · {getCategory(draft.category)?.name??draft.category}</span><h1 className="mt-1 font-display text-3xl font-black">{draft.title||"Nova matéria"}</h1><p className="mt-2 text-sm text-muted-foreground">Revisão determinística, auditável e local. Nenhum texto é enviado para um modelo externo.</p></div><div className="flex flex-wrap items-center gap-2"><span className={"rounded-full px-3 py-1 text-xs font-bold "+(readiness.state==="pronto"?"bg-green-100 text-green-800":readiness.state==="revisao-necessaria"?"bg-red-100 text-red-800":"bg-amber-100 text-amber-800")}>{readiness.state==="pronto"?"✓ Pronto para publicar":readiness.state==="revisao-necessaria"?"⚠ Revisão necessária":"• "+(readiness.state==="sem-revisao"?"Sem revisão":"Revisão desatualizada")}</span><button onClick={runReview} disabled={running} className="inline-flex items-center gap-2 rounded-md bg-primary px-4 py-2 text-sm font-bold text-primary-foreground"><SearchCheck size={17}/>{running?"Revisando…":"Revisar matéria"}</button></div></div>
  {message&&<div className="mb-4 rounded-md border bg-card px-4 py-3 text-sm">{message}</div>}
  <nav className="mb-4 flex gap-1 rounded-lg border bg-muted p-1"><Tab active={tab==="conteudo"} onClick={()=>setTab("conteudo")}>Conteúdo</Tab><Tab active={tab==="revisao"} onClick={()=>setTab("revisao")}>Revisão {openSuggestions.length>0&&<span className="ml-1 rounded-full bg-primary/15 px-1.5">{openSuggestions.length}</span>}</Tab><Tab active={tab==="seo"} onClick={()=>setTab("seo")}>SEO <span className="ml-1 rounded-full bg-foreground px-1.5 text-background">{score}</span></Tab></nav>
  {tab==="conteudo"&&<ContentEditor draft={draft} update={update}/>}
  {tab==="revisao"&&<ReviewPanel draft={draft} progress={progress} running={running} open={openSuggestions} agents={reviewAgents} onApply={applyOne} onIgnore={ignoreOne} onApplyAll={applyAll}/>}
  {tab==="seo"&&<SeoPanel draft={draft} update={update} checks={checks} score={score}/>}
  </section></div></main>;
}
function Tab({active,onClick,children}:{active:boolean;onClick:()=>void;children:React.ReactNode}){return <button onClick={onClick} className={"rounded-md px-4 py-2 text-xs font-bold "+(active?"bg-card shadow-sm":"text-muted-foreground")}>{children}</button>}
function ContentEditor({draft,update}:{draft:any;update:(p:any)=>void}){return <div className="grid gap-5 xl:grid-cols-[1fr_340px]"><div className="space-y-4 rounded-xl border bg-card p-5"><Field label="Título"><input value={draft.title} onChange={e=>update({title:e.target.value,slug:draft.slug||slugify(e.target.value)})} className="field-input text-xl font-bold"/></Field><Field label="Linha fina"><textarea value={draft.subtitle} onChange={e=>update({subtitle:e.target.value})} className="field-input min-h-20"/></Field><Field label="Resumo"><textarea value={draft.excerpt} onChange={e=>update({excerpt:e.target.value})} className="field-input min-h-24"/></Field><Field label="Texto"><textarea value={draft.body} onChange={e=>update({body:e.target.value})} className="field-input min-h-[480px] font-mono text-sm leading-6"/></Field></div><aside className="space-y-4"><div className="rounded-xl border bg-card p-5"><div className="mb-4 flex items-center gap-2 font-semibold"><FileCheck2 size={17}/> Publicação</div><Field label="Editoria"><select value={draft.category} onChange={e=>update({category:e.target.value})} className="field-input">{categories.map(c=><option key={c.slug} value={c.slug}>{c.name}</option>)}</select></Field><Field label="Status"><select value={draft.status} onChange={e=>update({status:e.target.value})} className="field-input"><option value="rascunho">Rascunho</option><option value="revisao">Revisão</option><option value="publicado">Publicado</option></select></Field><Field label="Slug"><input value={draft.slug} onChange={e=>update({slug:e.target.value})} className="field-input"/></Field></div><div className="rounded-xl border bg-card p-5"><div className="mb-3 flex items-center gap-2 font-semibold"><Eye size={16}/> Imagem principal</div>{draft.image?<img src={draft.image} alt="" className="aspect-video w-full rounded-md object-cover"/>:<div className="rounded-md border border-dashed p-8 text-center text-xs text-muted-foreground">Imagem não definida</div>}<div className="mt-2 text-[11px] text-muted-foreground">{draft.imageCredit||"Crédito pendente"}</div></div></aside></div>}
function ReviewPanel({draft,progress,running,open,agents,onApply,onIgnore,onApplyAll}:{draft:any;progress:Record<string,string>;running:boolean;open:Suggestion[];agents:any[];onApply:(s:Suggestion)=>void;onIgnore:(s:Suggestion)=>void;onApplyAll:()=>void}){return <div className="space-y-4">{draft.lastReview&&<div className="grid gap-3 md:grid-cols-4">{agents.map((a:any)=><div key={a.id} className="rounded-lg border bg-card p-4"><div className="text-[10px] font-bold tracking-wider text-muted-foreground">{progress[a.id]||"concluido"}</div><div className="mt-1 text-sm font-semibold">{a.name}</div><div className="mt-1 text-xs text-muted-foreground">{a.count} apontamentos · {a.durationMs} ms</div></div>)}</div>}{running&&<div className="rounded-lg border bg-card p-4"><div className="flex items-center gap-2 text-sm font-semibold"><RotateCcw className="animate-spin" size={15}/> Executando regras locais…</div><div className="mt-3 flex flex-wrap gap-2">{Object.entries(progress).map(([id,state])=><span key={id} className="rounded-full bg-muted px-2 py-1 text-[10px]">{id}: {state}</span>)}</div></div>}{draft.lastReview&&!running&&<div className="flex items-center justify-between rounded-lg border bg-card p-4"><div><div className="flex items-center gap-2 font-semibold"><ShieldCheck size={17}/>{open.length?open.length+" pontos para conferir":"Revisão sem pendências"}</div><div className="mt-1 text-xs text-muted-foreground">Motor: {draft.lastReview.engine.label}</div></div>{open.some(s=>s.fix)&&<button onClick={onApplyAll} className="rounded-md bg-foreground px-3 py-2 text-xs font-bold text-background">Aplicar correções seguras</button>}</div>}{open.length===0&&draft.lastReview?<div className="rounded-xl border bg-card p-10 text-center"><CheckCircle2 className="mx-auto" size={32}/><h2 className="mt-3 font-display text-2xl font-bold">Nenhum alerta pendente.</h2><p className="mt-2 text-sm text-muted-foreground">A matéria passou pelo conjunto atual de regras. Isso não substitui a apuração humana.</p></div>:<div className="space-y-3">{open.map(s=><SuggestionCard key={s.id} s={s} onApply={()=>onApply(s)} onIgnore={()=>onIgnore(s)}/>)}</div>}{draft.reviewHistory.length>0&&<details className="rounded-lg border bg-card p-4"><summary className="cursor-pointer text-sm font-semibold">Histórico de revisões ({draft.reviewHistory.length})</summary><div className="mt-3 space-y-2">{draft.reviewHistory.map((r:any)=><div key={r.id} className="flex justify-between border-t pt-2 text-xs"><span>{r.engineLabel}</span><span>{r.total} apontamentos · {new Date(r.finishedAt).toLocaleString("pt-BR")}</span></div>)}</div></details>}</div>}
function SuggestionCard({s,onApply,onIgnore}:{s:Suggestion;onApply:()=>void;onIgnore:()=>void}){return <div className="rounded-xl border bg-card p-5"><div className="flex flex-col gap-3 md:flex-row md:items-start md:justify-between"><div className="flex gap-3"><span className={"mt-0.5 rounded-full px-2 py-1 text-[10px] font-black "+(s.severity==="alta"?"bg-red-100 text-red-800":s.severity==="media"?"bg-amber-100 text-amber-800":"bg-blue-100 text-blue-800")}>{severityLabel[s.severity]}</span><div><div className="text-[10px] font-bold uppercase tracking-wider text-muted-foreground">{s.agentId} · {s.field}</div><p className="mt-1 font-semibold">{s.message}</p><p className="mt-2 rounded-md bg-muted p-3 font-mono text-xs leading-5">{s.excerpt}</p>{s.fix&&<div className="mt-2 text-xs text-muted-foreground">Correção segura disponível.</div>}</div></div><div className="flex shrink-0 gap-2"><button onClick={onIgnore} className="inline-flex items-center gap-1 rounded-md border px-3 py-2 text-xs"><X size={13}/> Ignorar</button>{s.fix&&<button onClick={onApply} className="inline-flex items-center gap-1 rounded-md bg-foreground px-3 py-2 text-xs font-bold text-background"><Check size={13}/> Aplicar</button>}</div></div></div>}
function SeoPanel({draft,update,checks,score}:{draft:any;update:(p:any)=>void;checks:any[];score:number}){const patchSeo=(p:any)=>update({seo:{...draft.seo,...p}});const previewPath="/noticia/"+(draft.slug||"slug-da-materia");return <div className="grid gap-5 xl:grid-cols-[1fr_360px]"><div className="space-y-4 rounded-xl border bg-card p-5"><div className="flex items-center justify-between"><div><span className="kicker">SAÚDE SEO</span><h2 className="mt-1 font-display text-3xl font-bold">Como a matéria será entendida.</h2></div><div className="text-right"><div className="font-display text-4xl font-black">{score}</div><div className="text-[10px] font-bold tracking-wider text-muted-foreground">AUDITORIA</div></div></div><Field label="Title tag"><input value={draft.seo.title} onChange={e=>patchSeo({title:e.target.value})} className="field-input"/><small className="text-muted-foreground">{effectiveSeoTitle(draft).length}/60 · sugestão: {suggestSeoTitle(draft)}</small></Field><Field label="Meta description"><textarea value={draft.seo.description} onChange={e=>patchSeo({description:e.target.value})} className="field-input min-h-24"/><small className="text-muted-foreground">{effectiveDescription(draft).length}/160 · sugestão: {suggestMetaDescription(draft)}</small></Field><Field label="Tema principal"><div className="flex gap-2"><input value={draft.seo.keyword} onChange={e=>patchSeo({keyword:e.target.value})} className="field-input"/><button type="button" onClick={()=>patchSeo({keyword:suggestKeyword(draft)})} className="shrink-0 rounded-md border px-3 text-xs font-bold">Sugerir</button></div></Field><Field label="Canonical"><input value={draft.seo.canonical} onChange={e=>patchSeo({canonical:e.target.value})} placeholder="Automático" className="field-input"/></Field><label className="flex items-center gap-2 text-sm"><input type="checkbox" checked={draft.seo.index} onChange={e=>patchSeo({index:e.target.checked})}/> Permitir indexação</label><div className="rounded-lg border bg-muted p-4"><div className="text-[10px] font-bold tracking-wider text-muted-foreground">PRÉVIA DO GOOGLE</div><div className="mt-2 text-lg text-blue-700">{effectiveSeoTitle(draft)||"Título da matéria"}</div><div className="text-xs text-green-700">pch-news.lovable.app{previewPath}</div><p className="mt-1 text-sm text-muted-foreground">{effectiveDescription(draft)||"A descrição da matéria aparecerá aqui."}</p></div></div><aside className="space-y-3">{checks.map(c=><div key={c.id} className="rounded-lg border bg-card p-4"><div className="flex items-center gap-2 font-semibold text-sm">{c.state==="ok"?<CheckCircle2 size={16}/>:c.state==="erro"?<AlertTriangle size={16}/>:<Info size={16}/>} {c.label}</div><p className="mt-1 text-xs leading-5 text-muted-foreground">{c.detail}</p></div>)}</aside></div>}
function Field({label,children}:{label:string;children:React.ReactNode}){return <label className="block space-y-1.5"><span className="text-[10px] font-bold uppercase tracking-wider text-muted-foreground">{label}</span>{children}</label>}
