import { bigint, boolean, int, mysqlEnum, mysqlTable, text, timestamp, varchar } from "drizzle-orm/mysql-core";

export const users = mysqlTable("users", { id: int("id").autoincrement().primaryKey(), openId: varchar("openId", { length: 64 }).notNull().unique(), name: text("name"), email: varchar("email", { length: 320 }), loginMethod: varchar("loginMethod", { length: 64 }), role: mysqlEnum("role", ["user", "admin", "columnist"]).default("user").notNull(), createdAt: timestamp("createdAt").defaultNow().notNull(), updatedAt: timestamp("updatedAt").defaultNow().onUpdateNow().notNull(), lastSignedIn: timestamp("lastSignedIn").defaultNow().notNull() });
export const articles = mysqlTable("articles", { id: varchar("id", { length: 96 }).primaryKey(), title: varchar("title", { length: 255 }).notNull(), category: varchar("category", { length: 120 }).notNull(), author: varchar("author", { length: 180 }).notNull(), authorOpenId: varchar("authorOpenId", { length: 64 }), summary: text("summary").notNull(), date: varchar("date", { length: 32 }).notNull(), updated: varchar("updated", { length: 64 }).notNull(), status: mysqlEnum("status", ["published", "draft", "scheduled", "archived"]).notNull().default("draft"), views: int("views").notNull().default(0), image: text("image").notNull(), bodyHtml: text("bodyHtml").notNull(), scheduledAt: bigint("scheduledAt", { mode: "number" }), tags: text("tags").notNull(), youtubeUrl: text("youtubeUrl"), socialLinks: text("socialLinks"), slug: varchar("slug", { length: 255 }), seoTitle: varchar("seoTitle", { length: 255 }), metaDescription: text("metaDescription"), canonicalUrl: text("canonicalUrl"), focusKeyword: varchar("focusKeyword", { length: 180 }), ogTitle: varchar("ogTitle", { length: 255 }), ogDescription: text("ogDescription"), imageAlt: varchar("imageAlt", { length: 255 }), noindex: boolean("noindex").default(false).notNull(), createdAt: timestamp("createdAt").defaultNow().notNull(), updatedAt: timestamp("updatedAt").defaultNow().onUpdateNow().notNull() });
export const viewEvents = mysqlTable("viewEvents", { id: varchar("id", { length: 96 }).primaryKey(), articleId: varchar("articleId", { length: 96 }).notNull(), visitorId: varchar("visitorId", { length: 128 }).notNull(), viewedAtMs: bigint("viewedAtMs", { mode: "number" }).notNull() });
export const comments = mysqlTable("comments", { id: varchar("id", { length: 96 }).primaryKey(), articleId: varchar("articleId", { length: 96 }).notNull(), name: varchar("name", { length: 160 }).notNull(), text: text("text").notNull(), createdAtMs: bigint("createdAtMs", { mode: "number" }).notNull(), status: mysqlEnum("status", ["pending", "approved", "rejected"]).notNull().default("pending"), reply: text("reply"), repliedBy: varchar("repliedBy", { length: 180 }), repliedAtMs: bigint("repliedAtMs", { mode: "number" }) });
export const columnistProfiles = mysqlTable("columnistProfiles", { slug: varchar("slug", { length: 96 }).primaryKey(), name: varchar("name", { length: 160 }).notNull(), beat: varchar("beat", { length: 180 }).notNull(), bio: text("bio").notNull(), photo: text("photo").notNull(), instagram: varchar("instagram", { length: 160 }).notNull(), facebook: varchar("facebook", { length: 160 }).notNull(), x: varchar("x", { length: 160 }).notNull(), linkedin: varchar("linkedin", { length: 180 }).notNull(), updatedAt: timestamp("updatedAt").defaultNow().onUpdateNow().notNull() });
export const adRequests = mysqlTable("adRequests", { id: varchar("id", { length: 96 }).primaryKey(), business: varchar("business", { length: 180 }).notNull(), contact: varchar("contact", { length: 240 }).notNull(), packageName: varchar("packageName", { length: 160 }).notNull(), message: text("message").notNull(), status: mysqlEnum("status", ["received", "reviewing", "approved"]).notNull().default("received"), createdAtMs: bigint("createdAtMs", { mode: "number" }).notNull() });
export const columnistInvites = mysqlTable("columnistInvites", { id: varchar("id", { length: 96 }).primaryKey(), email: varchar("email", { length: 320 }).notNull(), name: varchar("name", { length: 160 }).notNull(), tokenHash: varchar("tokenHash", { length: 128 }).notNull().unique(), expiresAtMs: bigint("expiresAtMs", { mode: "number" }).notNull(), createdAtMs: bigint("createdAtMs", { mode: "number" }).notNull(), acceptedAtMs: bigint("acceptedAtMs", { mode: "number" }), revokedAtMs: bigint("revokedAtMs", { mode: "number" }) });
export const articleAudit = mysqlTable("articleAudit", { id: varchar("id", { length: 96 }).primaryKey(), articleId: varchar("articleId", { length: 96 }).notNull(), actorOpenId: varchar("actorOpenId", { length: 64 }).notNull(), actorName: varchar("actorName", { length: 180 }).notNull(), action: varchar("action", { length: 64 }).notNull(), beforeJson: text("beforeJson"), afterJson: text("afterJson"), createdAtMs: bigint("createdAtMs", { mode: "number" }).notNull() });
export const editorialFreedomReviews = mysqlTable("editorialFreedomReviews", { id: varchar("id", { length: 96 }).primaryKey(), articleId: varchar("articleId", { length: 96 }).notNull(), rulesetVersion: varchar("rulesetVersion", { length: 64 }).notNull(), status: mysqlEnum("status", ["pass", "review", "block"]).notNull(), score: int("score").notNull(), contentType: varchar("contentType", { length: 16 }).notNull(), autonomyAnswer: varchar("autonomyAnswer", { length: 16 }).notNull(), checksJson: text("checksJson").notNull(), actorOpenId: varchar("actorOpenId", { length: 64 }).notNull(), createdAtMs: bigint("createdAtMs", { mode: "number" }).notNull() });
export const editorialAgentRuns = mysqlTable("editorialAgentRuns", { id: varchar("id", { length: 96 }).primaryKey(), articleId: varchar("articleId", { length: 96 }).notNull(), agentId: varchar("agentId", { length: 96 }).notNull(), agentName: varchar("agentName", { length: 180 }).notNull(), status: mysqlEnum("status", ["pass", "review", "block"]).notNull(), findingsJson: text("findingsJson").notNull(), outputJson: text("outputJson").notNull(), actorOpenId: varchar("actorOpenId", { length: 64 }).notNull(), createdAtMs: bigint("createdAtMs", { mode: "number" }).notNull() });

export type User = typeof users.$inferSelect; export type InsertUser = typeof users.$inferInsert; export type Article = typeof articles.$inferSelect; export type InsertArticle = typeof articles.$inferInsert; export type ViewEvent = typeof viewEvents.$inferSelect; export type InsertViewEvent = typeof viewEvents.$inferInsert; export type Comment = typeof comments.$inferSelect; export type InsertComment = typeof comments.$inferInsert; export type ColumnistProfile = typeof columnistProfiles.$inferSelect; export type InsertColumnistProfile = typeof columnistProfiles.$inferInsert; export type AdRequest = typeof adRequests.$inferSelect; export type InsertAdRequest = typeof adRequests.$inferInsert; export type ColumnistInvite = typeof columnistInvites.$inferSelect; export type InsertColumnistInvite = typeof columnistInvites.$inferInsert; export type ArticleAudit = typeof articleAudit.$inferSelect; export type InsertArticleAudit = typeof articleAudit.$inferInsert; export type EditorialAgentRun = typeof editorialAgentRuns.$inferSelect; export type InsertEditorialAgentRun = typeof editorialAgentRuns.$inferInsert;
