import { FormEvent, useState } from "react";
import { Megaphone, Send, ShieldCheck, Sparkles } from "lucide-react";
import { AdRequest, persistAdRequests, readAdRequests } from "@/lib/editorial";

const packages = [{ name: "Destaque local", price: "R$ 290", detail: "7 dias · chamada na home", accent: "blue" }, { name: "Marca em foco", price: "R$ 690", detail: "15 dias · home + editoria", accent: "gold" }, { name: "Especial PCH News", price: "R$ 1.290", detail: "30 dias · campanha editorial", accent: "navy" }];
export default function Ads({ notify }: { notify: (message: string) => void }) {
  const [requests, setRequests] = useState<AdRequest[]>(readAdRequests);
  const [form, setForm] = useState({ business: "", contact: "", packageName: packages[0].name, message: "" });
  const submit = (event: FormEvent) => { event.preventDefault(); if (!form.business.trim() || !form.contact.trim()) { notify("Informe sua empresa e um contato."); return; } const next = [{ id: `ad-${Date.now()}`, ...form, status: "received" as const, createdAtMs: Date.now() }, ...requests]; setRequests(next); persistAdRequests(next); setForm({ ...form, business: "", contact: "", message: "" }); notify("Solicitação recebida. A equipe comercial entrará em contato."); };
  return <div className="ads-page"><div className="admin-heading compact"><div><span className="admin-kicker">MONETIZAÇÃO EDITORIAL</span><h1>Anúncios<span>.</span></h1><p>Crie oportunidades de divulgação com transparência e contexto para a audiência do PCH News.</p></div><span className="ad-safe-badge"><ShieldCheck size={15} /> Sem cobrança automática</span></div><section className="ad-hero panel"><div><span className="admin-kicker">PCH NEWS ADS</span><h2>Sua marca pode ser a próxima notícia.</h2><p>Escolha um formato de presença, envie seu briefing e receba uma proposta. Esta demonstração registra apenas o interesse localmente.</p></div><Megaphone size={58} /></section><div className="ad-layout"><section><div className="section-heading"><div><span className="admin-kicker">FORMATOS</span><h2>Pacotes de divulgação</h2></div></div><div className="ad-packages">{packages.map((item) => <button key={item.name} className={`ad-package ${item.accent} ${form.packageName === item.name ? "selected" : ""}`} onClick={() => setForm({ ...form, packageName: item.name })}><span>{item.name}</span><strong>{item.price}</strong><small>{item.detail}</small><Sparkles size={15} /></button>)}</div></section><form className="panel ad-form" onSubmit={submit}><div className="panel-heading"><div><span className="admin-kicker">PRÓXIMO PASSO</span><h2>Solicitar proposta</h2></div><Send size={18} /></div><label>Empresa<input value={form.business} onChange={(e) => setForm({ ...form, business: e.target.value })} placeholder="Nome da marca" /></label><label>Contato<input value={form.contact} onChange={(e) => setForm({ ...form, contact: e.target.value })} placeholder="WhatsApp ou e-mail" /></label><label>Briefing<textarea value={form.message} onChange={(e) => setForm({ ...form, message: e.target.value })} placeholder="Conte o que deseja divulgar" /></label><button className="primary-cta" type="submit"><Send size={15} /> Enviar interesse</button></form></div>{requests.length > 0 && <section className="panel ad-requests"><div className="panel-heading"><div><span className="admin-kicker">CRM COMERCIAL</span><h2>Solicitações recebidas</h2></div><span>{requests.length} registro(s)</span></div>{requests.map((item) => <div className="ad-request" key={item.id}><div><strong>{item.business}</strong><small>{item.contact} · {item.packageName}</small></div><span>{item.status === "received" ? "Recebido" : item.status}</span></div>)}</section>}</div>;
}
