import { Download, FileSpreadsheet, FileText, History, Search, UserRound } from "lucide-react";
import { useMemo, useState } from "react";

export type AuditEntry = { id: string; articleId: string; articleTitle?: string | null; actorOpenId: string; actorName: string; action: string; beforeJson: string | null; afterJson: string | null; createdAtMs: number };

function summarize(entry: AuditEntry) {
  let after: Record<string, unknown> = {};
  let before: Record<string, unknown> = {};
  try { after = entry.afterJson ? JSON.parse(entry.afterJson) : {}; before = entry.beforeJson ? JSON.parse(entry.beforeJson) : {}; } catch { /* mantém o resumo básico */ }
  const labels: Record<string, string> = { title: "título", category: "editoria", status: "status", summary: "resumo", author: "autor" };
  const changes = Object.keys(labels).filter((key) => before[key] !== after[key]).map((key) => labels[key]);
  return changes.length ? `Alterou ${changes.join(", ")}` : entry.action === "created" ? "Criou a publicação" : "Atualizou o conteúdo";
}
function csvEscape(value: string) { return `"${value.replace(/"/g, '""')}"`; }
function downloadBlob(content: BlobPart, type: string, filename: string) { const url = URL.createObjectURL(new Blob([content], { type })); const link = document.createElement("a"); link.href = url; link.download = filename; link.click(); URL.revokeObjectURL(url); }
function articleLabel(entry: AuditEntry) { return entry.articleTitle || `Publicação sem título (${entry.articleId})`; }
function exportCsv(entries: AuditEntry[]) { const rows = [["Data", "Notícia", "Responsável", "Ação", "Descrição"], ...entries.map((entry) => [new Date(entry.createdAtMs).toLocaleString("pt-BR"), articleLabel(entry), entry.actorName, entry.action === "created" ? "Criação" : "Edição", summarize(entry)])]; downloadBlob(rows.map((row) => row.map(csvEscape).join(",")).join("\r\n"), "text/csv;charset=utf-8", `pch-news-auditoria-${new Date().toISOString().slice(0, 10)}.csv`); }
function pdfEscape(value: string) { return value.replace(/[\\()]/g, "\\$&").replace(/[^\x20-\x7E]/g, "?"); }
function exportPdf(entries: AuditEntry[]) { const lines = ["PCH NEWS - HISTORICO DE AUDITORIA", `Exportado em ${new Date().toLocaleString("pt-BR")}`, "", ...entries.flatMap((entry) => [new Date(entry.createdAtMs).toLocaleString("pt-BR") + " | " + (entry.action === "created" ? "CRIACAO" : "EDICAO"), entry.actorName + " - " + articleLabel(entry), summarize(entry), ""])]; const commands = ["BT", "/F1 10 Tf", "50 800 Td", ...lines.slice(0, 55).map((line) => "(" + pdfEscape(line.slice(0, 105)) + ") Tj 0 -14 Td"), "ET"].join("\n"); const objects = ["<< /Type /Catalog /Pages 2 0 R >>", "<< /Type /Pages /Kids [3 0 R] /Count 1 >>", "<< /Type /Page /Parent 2 0 R /MediaBox [0 0 595 842] /Resources << /Font << /F1 4 0 R >> >> /Contents 5 0 R >>", "<< /Type /Font /Subtype /Type1 /BaseFont /Helvetica >>", "<< /Length " + commands.length + " >>\nstream\n" + commands + "\nendstream"]; let pdf = "%PDF-1.4\n"; const offsets: number[] = [0]; objects.forEach((object, index) => { offsets.push(pdf.length); pdf += (index + 1) + " 0 obj\n" + object + "\nendobj\n"; }); const xref = pdf.length; const table = offsets.slice(1).map((offset) => String(offset).padStart(10, "0") + " 00000 n ").join("\n"); pdf += "xref\n0 " + (objects.length + 1) + "\n0000000000 65535 f \n" + table + "\ntrailer\n<< /Size " + (objects.length + 1) + " /Root 1 0 R >>\nstartxref\n" + xref + "\n%%EOF"; downloadBlob(pdf, "application/pdf", `pch-news-auditoria-${new Date().toISOString().slice(0, 10)}.pdf`); }

export default function Audit({ entries }: { entries: AuditEntry[] }) {
  const [query, setQuery] = useState(""); const [author, setAuthor] = useState("all"); const [action, setAction] = useState("all"); const [fromDate, setFromDate] = useState(""); const [toDate, setToDate] = useState("");
  const authors = useMemo(() => Array.from(new Set(entries.map((entry) => entry.actorName))).sort(), [entries]);
  const filtered = useMemo(() => entries.filter((entry) => { const date = new Date(entry.createdAtMs); const fromOk = !fromDate || date >= new Date(`${fromDate}T00:00:00`); const toOk = !toDate || date <= new Date(`${toDate}T23:59:59.999`); const haystack = `${articleLabel(entry)} ${entry.actorName} ${summarize(entry)}`.toLowerCase(); return fromOk && toOk && (author === "all" || entry.actorName === author) && (action === "all" || entry.action === action) && (!query || haystack.includes(query.toLowerCase())); }), [entries, query, author, action, fromDate, toDate]);
  const clearFilters = () => { setQuery(""); setAuthor("all"); setAction("all"); setFromDate(""); setToDate(""); };
  return <div className="audit-page"><div className="admin-heading compact"><div><span className="admin-kicker">RASTREABILIDADE EDITORIAL</span><h1>Auditoria<span>.</span></h1><p>Veja quem alterou cada publicação, quando e quais campos foram modificados.</p></div><span className="team-count"><History size={16} /> {filtered.length} de {entries.length}</span></div><section className="panel audit-panel"><div className="audit-toolbar"><div className="admin-search"><Search size={16} /><input value={query} onChange={(event) => setQuery(event.target.value)} placeholder="Buscar notícia ou responsável" /></div><select value={author} onChange={(event) => setAuthor(event.target.value)}><option value="all">Todos os autores</option>{authors.map((item) => <option key={item}>{item}</option>)}</select><select value={action} onChange={(event) => setAction(event.target.value)}><option value="all">Todas as ações</option><option value="created">Criações</option><option value="updated">Edições</option></select><label>De<input type="date" value={fromDate} onChange={(event) => setFromDate(event.target.value)} /></label><label>Até<input type="date" value={toDate} onChange={(event) => setToDate(event.target.value)} /></label><button className="audit-clear" onClick={clearFilters}>Limpar</button></div><div className="audit-export-bar"><span>Exportar os {filtered.length} registros filtrados</span><div><button onClick={() => exportCsv(filtered)}><FileSpreadsheet size={14} /> CSV</button><button onClick={() => exportPdf(filtered)}><FileText size={14} /> PDF</button><Download size={15} /></div></div>{filtered.length === 0 ? <div className="media-empty"><History size={28} /><strong>Nenhuma alteração encontrada</strong><span>Ajuste os filtros para ampliar a busca.</span></div> : <div className="audit-list">{filtered.map((entry) => <article className="audit-row" key={entry.id}><div className="audit-icon"><UserRound size={15} /></div><div className="audit-copy"><strong>{summarize(entry)}</strong><span>Notícia <b>{articleLabel(entry)}</b></span><small>Por {entry.actorName} · {new Date(entry.createdAtMs).toLocaleString("pt-BR")}</small></div><em>{entry.action === "created" ? "Criação" : "Edição"}</em></article>)}</div>}</section></div>;
}
