import { ArrowRight, BookOpen, Facebook, Globe, Instagram, Linkedin, Twitter, ExternalLink } from "lucide-react";
import { Link, useRoute } from "wouter";
import { trpc } from "@/lib/trpc";
import { NewsArticle } from "@/lib/news";
import officialLogoUrl from "@/assets/pch-news-official-current.svg";
import { editorialImageUrl } from "@/lib/editorialImage";
import PageMeta from "@/components/PageMeta";
import PublicFooter from "@/components/PublicFooter";
const LOGO_URL = officialLogoUrl;
const imageUrl = (article: NewsArticle) => editorialImageUrl(article);
const slugify = (value: string) => value.toLowerCase().normalize("NFD").replace(/[\u0300-\u036f]/g, "").replace(/[^a-z0-9]+/g, "-").replace(/(^-|-$)/g, "");
function readProducts(profile:any){ if(!profile?.commercialApproved) return []; try { const value=profile?.productsJson; const parsed=typeof value==="string"?JSON.parse(value||"[]"):value; return Array.isArray(parsed)?parsed.filter((item:any)=>item?.active!==false && item?.url):[]; } catch { return []; } }
function externalUrl(value:string){ return /^https?:\/\//.test(value) ? value : "https://"+value.replace(/^\/+/, ""); }
export default function ColumnistProfile() {
  const [, columnistParams] = useRoute("/colunista/:slug");
  const [, teamParams] = useRoute("/equipe/:slug");
  const params = columnistParams || teamParams;
  const { data } = trpc.editorial.bootstrap.useQuery(undefined, { retry:false });
  const profile = params?.slug ? data?.profiles?.find((item:any)=>item.slug===params.slug) : undefined;
  const articles: NewsArticle[] = (data?.articles || []).filter((article:any) => article.status==="published" && ((article.authorProfileSlug && article.authorProfileSlug===params?.slug) || slugify(article.author)===params?.slug)).map((article:any)=>({...article,tags:typeof article.tags==="string"?(()=>{try{return JSON.parse(article.tags||"[]")}catch{return[]}})():article.tags||[],socialLinks:typeof article.socialLinks==="string"?(()=>{try{return JSON.parse(article.socialLinks||"{}")}catch{return{}}})():article.socialLinks||{},scheduledAt:article.scheduledAt?new Date(Number(article.scheduledAt)).toISOString().slice(0,16):undefined}));
  if(!profile) return <div className="article-page empty-article"><img className="article-logo" src={LOGO_URL} alt="PCH News"/><h1>Perfil não encontrado.</h1><Link className="primary-cta" href="/equipe">Voltar para a equipe</Link></div>;
  const products=readProducts(profile);
  const roleLabel=profile.beat || (profile.role==="columnist" ? "Colunista" : "Equipe PCH News");
  return <div className="site-shell public-module-page"><PageMeta title={`${profile.name} — Equipe PCH News`} description={profile.bio || `${profile.name} faz parte da equipe do PCH News.`} canonicalPath={`/equipe/${profile.slug}`}/>
    <header className="public-module-header team-profile-header"><div className="container public-module-header-inner"><Link href="/" className="public-module-brand"><img src={LOGO_URL} alt="PCH News"/><span>Equipe <strong>PCH News</strong></span></Link><Link href="/equipe" className="secondary-cta">Equipe PCH News</Link></div></header>
    <main className="container team-profile-page">
      <section className="team-profile-hero"><div className="team-profile-photo">{profile.photo?<img src={profile.photo} alt={profile.name} onError={(e)=>{e.currentTarget.style.display="none";e.currentTarget.parentElement?.classList.add("photo-fallback");}}/>:<span>{String(profile.name||"PN").split(/\s+/).filter(Boolean).slice(0,2).map((x:string)=>x[0]).join("").toUpperCase()}</span>}<span className="team-profile-photo-fallback">{String(profile.name||"PN").split(/\s+/).filter(Boolean).slice(0,2).map((x:string)=>x[0]).join("").toUpperCase()}</span></div><div className="team-profile-intro"><span className="eyebrow gold">EQUIPE PCH NEWS · {String(profile.role||"COLUNISTA").toUpperCase()}</span><h1>{profile.name}</h1><strong>{roleLabel}</strong><p>{profile.bio || "Perfil profissional em construção. Em breve, esta página reunirá a apresentação e as publicações deste profissional."}</p><div className="team-profile-links">{profile.instagram&&<a href={externalUrl(profile.instagram.startsWith("@")?`https://instagram.com/${profile.instagram.slice(1)}`:profile.instagram)} target="_blank" rel="noreferrer"><Instagram size={15}/> Instagram</a>}{profile.facebook&&<a href={externalUrl(profile.facebook)} target="_blank" rel="noreferrer"><Facebook size={15}/> Facebook</a>}{profile.x&&<a href={externalUrl(profile.x.startsWith("@")?`https://x.com/${profile.x.slice(1)}`:profile.x)} target="_blank" rel="noreferrer"><Twitter size={15}/> X</a>}{profile.linkedin&&<a href={externalUrl(profile.linkedin)} target="_blank" rel="noreferrer"><Linkedin size={15}/> LinkedIn</a>}{profile.tiktok&&<a href={externalUrl(profile.tiktok.startsWith("@")?`https://tiktok.com/@${profile.tiktok.slice(1)}`:profile.tiktok)} target="_blank" rel="noreferrer">TikTok</a>}{profile.website&&<a href={externalUrl(profile.website)} target="_blank" rel="noreferrer"><Globe size={15}/> Site</a>}</div></div></section>
      {products.length>0 && <section className="team-commercial-block"><div className="section-heading large-heading"><div><span className="eyebrow gold">DIVULGAÇÃO DO PROFISSIONAL</span><h2>Produtos e serviços</h2></div></div><p className="team-commercial-note">Conteúdo comercial apresentado pelo próprio profissional. Não constitui recomendação editorial do PCH News.</p><div className="team-product-grid">{products.map((item:any,index:number)=><article className="team-product-card" key={index}>{item.imageUrl&&<img src={item.imageUrl} alt=""/>}<div><span>APRESENTAÇÃO PROFISSIONAL</span><h3>{item.title}</h3><p>{item.description}</p><a href={externalUrl(item.url)} target="_blank" rel="noreferrer">{item.ctaLabel||"Conheça"} <ExternalLink size={14}/></a></div></article>)}</div></section>}
      <section className="profile-stories"><div className="section-heading large-heading"><div><span className="eyebrow">ARQUIVO DO PROFISSIONAL</span><h2>Publicações de {profile.name}</h2></div><div className="heading-rule"><span>{articles.length} histórias</span></div></div>{articles.length?<div className="profile-story-grid">{articles.map((article)=><article className="profile-story" key={article.id}><Link href={`/materia/${article.slug||article.id}`}><img src={imageUrl(article)} alt={article.title} onError={(e)=>{e.currentTarget.src=LOGO_URL}}/><div><span className="category-tag">{article.category}</span><h3>{article.title}</h3><p>{article.summary}</p><span className="read-more">Ler matéria <ArrowRight size={14}/></span></div></Link></article>)}</div>:<div className="profile-empty">Ainda não há publicações assinadas por este profissional.</div>}</section>
    </main><PublicFooter/></div>;
}