import { ArrowRight, LockKeyhole, ShieldCheck } from "lucide-react";
import { useEffect, useState } from "react";
import { useLocation } from "wouter";
import { startLogin } from "@/const";
import { useAuth } from "@/_core/hooks/useAuth";
import { supabase } from "@/lib/supabase";
const LOGO_URL = "/brand/logo.jpg?v=4";
const OWNER_EMAIL = "pchnews.oficial@gmail.com";
export default function Login() {
  const [, navigate] = useLocation(); const { user, loading, error: authError } = useAuth(); const [email, setEmail] = useState(""); const [message, setMessage] = useState(""); const [sending, setSending] = useState(false); const [googleError, setGoogleError] = useState("");
  useEffect(() => { if (!loading && user) navigate("/admin"); }, [loading, user, navigate]);
  return <main className="login-shell"><div className="login-orbit login-orbit-one" /><div className="login-orbit login-orbit-two" /><section className="login-card"><div className="login-brand"><img src={LOGO_URL} alt="PCH News" /><span>STUDIO</span></div><div className="login-intro"><span className="admin-kicker">ACESSO OFICIAL</span><h1>Entre na sua<br /><em>redação.</em></h1><p>Use sua conta Google para acompanhar publicações, administrar a equipe e proteger o conteúdo do PCH News.</p></div><div className="official-login-card"><div className="official-login-icon"><LockKeyhole size={20} /></div><div><strong>Autenticação Supabase</strong><span>Login com Google e sessão gerenciada pelo Supabase.</span></div></div><button className="login-submit" type="button" onClick={async () => { setGoogleError(""); const error = await startLogin(); if (error) setGoogleError(error.message); }}><span>Entrar com Google</span><ArrowRight size={16} /></button><div className="login-demo-note">Acesso administrativo direto: <strong>{OWNER_EMAIL}</strong>. Colunistas entram somente por convite individual.</div><form onSubmit={async (event) => { event.preventDefault(); const normalized = email.trim().toLowerCase(); if (!normalized) return; if (normalized !== OWNER_EMAIL) { setMessage("Acesso direto por e-mail é exclusivo do administrador. Colunistas entram pelo convite individual recebido por e-mail."); return; } setSending(true); setMessage(""); const { error } = await supabase.auth.signInWithOtp({ email: normalized, options: { shouldCreateUser: false } }); setSending(false); setMessage(error ? error.message : "Link de acesso enviado. Confira seu e-mail para entrar."); }}><input aria-label="E-mail editorial" type="email" value={email} onChange={(event) => setEmail(event.target.value)} placeholder="seu e-mail" required style={{ width: "100%", marginBottom: 10 }} /><button className="login-submit" type="submit" disabled={sending}><span>{sending ? "Enviando link…" : "Entrar por e-mail"}</span><ArrowRight size={16} /></button></form>{(googleError || authError) && <div className="login-demo-note">{googleError || authError?.message}</div>}<div className="login-security"><ShieldCheck size={16} /><span>Ambiente editorial protegido<br /><small>Administradores e colunistas recebem permissões diferentes.</small></span></div>{message && <div className="login-demo-note">{message}</div>}</section><footer className="login-footer">© 2026 PCH News · Notícias para libertar a mente.</footer></main>;
}
