import { FormEvent, useEffect, useState } from "react";
import { CheckCircle2, Megaphone, Send, ShieldCheck, Upload, X } from "lucide-react";
import { Link } from "wouter";
import { trpc } from "@/lib/trpc";
import PublicFooter from "@/components/PublicFooter";
import PageMeta from "@/components/PageMeta";

import officialLogoUrl from "@/assets/pch-news-official-current.svg";
const LOGO_URL = officialLogoUrl;
const formatCards = [
  { id: "banner-home", name: "Banner na home", where: "Faixa em destaque entre as notícias da página inicial, no computador e no celular.", tag: "Mais visto" },
  { id: "lateral-home", name: "Lateral na home", where: "Espaço ao lado da manchete principal, junto às mais lidas." },
  { id: "topo-materia", name: "Topo das matérias", where: "Faixa acima de cada matéria lida no portal." },
  { id: "patrocinio-editoria", name: "Patrocínio de editoria", where: "Sua marca apresentando uma editoria, como Colunas ou Agenda." },
  { id: "publieditorial", name: "Conteúdo patrocinado", where: "Matéria sobre sua empresa, produzida com a redação e identificada como publicidade." },
  { id: "evento-agenda", name: "Evento na Agenda PCH", where: "Destaque do seu evento na agenda e na home." },
  { id: "projeto-especial", name: "Projeto especial", where: "Campanha sob medida: série de conteúdos, cobertura ou ação combinada." },
];
const formats = [...formatCards.map((f) => f.name), "Outro"];
const payments = ["Pix", "Boleto bancário", "Cartão de crédito", "Transferência bancária", "A combinar"];

export default function PublicAds() {
  const create = trpc.adRequests.create.useMutation();
  const uploadAsset = trpc.adRequests.uploadAsset.useMutation();
  const trackingToken = typeof window !== "undefined" ? new URLSearchParams(window.location.search).get("token") || "" : "";
  const tracking = trpc.adAnalytics.report.useQuery({ token: trackingToken }, { enabled: Boolean(trackingToken), retry: false, refetchInterval: 10000, refetchIntervalInBackground: true });
  const [sent, setSent] = useState(false);
  const [assetUploading, setAssetUploading] = useState(false);
  const [form, setForm] = useState({ business:"", contactName:"", email:"", phone:"", city:"", website:"", socials:"", adType:(() => { if (typeof window === "undefined") return formats[0]; const q = new URLSearchParams(window.location.search).get("formato"); return formatCards.find((f) => f.id === q)?.name || formats[0]; })(), payment:payments[0], budget:"", period:"", message:"", consent:false, destinationUrl:"", creativeUrl:"", creativeNeed:"no_artwork_yet" });
  useEffect(() => { if (window.location.hash) document.getElementById(window.location.hash.slice(1))?.scrollIntoView({ behavior: "smooth", block: "start" }); }, []);
  const chooseFormat = (name: string) => { setForm((f) => ({ ...f, adType: name })); document.getElementById("proposta")?.scrollIntoView({ behavior: "smooth", block: "start" }); };
  const update=(key:string,value:string|boolean)=>setForm(f=>({...f,[key]:value}));
  const updateCreativeNeed=(value:string)=>setForm(f=>({...f,creativeNeed:value as "client_artwork"|"pch_creation"|"no_artwork_yet"}));
  const uploadCreative=async(file:File)=>{
    const allowed=["image/png","image/jpeg","image/webp","image/gif"];
    if(!allowed.includes(file.type)){return;}
    if(file.size>5*1024*1024){return;}
    setAssetUploading(true);
    try{
      const bytes=new Uint8Array(await file.arrayBuffer()); let binary="";
      bytes.forEach(byte=>{binary+=String.fromCharCode(byte);});
      const result=await uploadAsset.mutateAsync({fileName:file.name,contentType:file.type as "image/png"|"image/jpeg"|"image/webp"|"image/gif",base64:btoa(binary)});
      update("creativeUrl",result.url);
      update("creativeNeed","client_artwork");
    } finally { setAssetUploading(false); }
  };
  const submit=async(e:FormEvent)=>{
    e.preventDefault();
    if(!form.business.trim()||!form.contactName.trim()||!form.email.trim()||!form.phone.trim()||!form.message.trim()||!form.consent){ return; }
    const { payment, ...rest } = form; await create.mutateAsync({ ...rest, creativeNeed: rest.creativeNeed as "client_artwork" | "pch_creation" | "no_artwork_yet", message: `Forma de pagamento preferida: ${payment}\n\n${form.message}`, consent: true });
    setSent(true);
  };
  if (trackingToken) return <div className="site-shell public-module-page"><PageMeta title="Acompanhamento da campanha — PCH News" description="Relatório privado de desempenho da campanha publicitária." canonicalPath="/anuncie" /><header className="public-module-header"><div className="container public-module-header-inner"><Link href="/" className="public-module-brand"><img src={LOGO_URL} alt="PCH News"/><span>Informação para <strong>libertar a mente.</strong></span></Link></div></header><main><section className="container public-hero"><div><span className="eyebrow gold">PCH NEWS ADS · ACOMPANHAMENTO</span><h1>Campanha em acompanhamento.</h1><p>Este painel mostra dados agregados de exposição e interação da campanha. A identidade pessoal de quem acessa ou clica não é exibida.</p></div></section><section className="container ad-report-grid"><div className="ad-report-card"><span>IMPRESSÕES</span><strong>{tracking.data?.impressions ?? "—"}</strong><small>vezes em que a campanha foi exibida</small></div><div className="ad-report-card"><span>CLIQUES</span><strong>{tracking.data?.clicks ?? "—"}</strong><small>acessos ao destino da campanha</small></div><div className="ad-report-card"><span>CTR</span><strong>{tracking.data ? `${tracking.data.ctr}%` : "—"}</strong><small>cliques em relação às impressões</small></div><div className="public-form-card"><div className="public-form-heading"><span className="public-kicker">CAMPANHA</span><h2>{tracking.data?.campaign?.name || "Carregando…"}</h2><p>Atualização automática. O painel é privado e destinado ao contratante da campanha.</p></div>{tracking.error&&<div className="form-error">{tracking.error.message}</div>}<div className="ad-report-events">{(tracking.data?.events||[]).slice(0,20).map((event:any,i:number)=><div key={i}><span>{event.eventType==="click"?"Clique":"Impressão"}</span><time>{new Date(event.occurredAtMs).toLocaleString("pt-BR")}</time><small>{event.deviceType==="mobile"?"Celular":"Computador"}</small></div>)}</div></div></section></main><PublicFooter/></div>;
  return <div className="site-shell public-module-page"><PageMeta title="Anuncie no PCH News" description="Solicite uma proposta comercial para anunciar no PCH News." canonicalPath="/anuncie" />
    <header className="public-module-header"><div className="container public-module-header-inner"><Link href="/" className="public-module-brand"><img src={LOGO_URL} alt="PCH News"/><span>Informação para <strong>libertar a mente.</strong></span></Link><nav><Link href="/">Notícias</Link><Link href="/institucional">Institucional</Link><Link href="/lei">Lei &amp; Justiça</Link></nav></div></header>
    <main>
      <section className="container public-hero ad-public-hero"><div><span className="eyebrow gold">PCH NEWS ADS · COMERCIAL</span><h1>Sua marca pode ocupar <em>um espaço claro.</em></h1><p>Apresente sua empresa, produto ou serviço ao PCH News. Escolha o formato abaixo, diga como prefere pagar e receba a proposta da equipe comercial.</p></div><div className="ad-hero-mark"><Megaphone size={44}/><span>PUBLICIDADE<br/><strong>IDENTIFICADA</strong></span></div></section>
      <section className="container ads-public-grid">
        <div className="ads-public-info"><span className="public-kicker" id="formatos">FORMATOS</span><h2>Presença comercial com transparência.</h2><p>Clique no formato que você quer. Valores, disponibilidade e condições vêm na proposta comercial, conforme o período e o projeto.</p><div className="ad-format-cards">{formatCards.map(f=><button type="button" key={f.id} className={"ad-format-card"+(form.adType===f.name?" is-selected":"")} onClick={()=>chooseFormat(f.name)}><span className="ad-format-top"><strong>{f.name}</strong>{f.tag&&<em>{f.tag}</em>}</span><span>{f.where}</span><small>{form.adType===f.name?"Selecionado ✓":"Escolher este formato →"}</small></button>)}</div><div className="ads-trust"><ShieldCheck size={20}/><div><strong>Sem cobrança automática</strong><p>Este formulário registra apenas uma solicitação comercial. A equipe entra em contato antes de qualquer contratação.</p></div></div></div>
        <div className="public-form-card" id="proposta">{sent?<div className="form-success"><CheckCircle2 size={42}/><span className="public-kicker">SOLICITAÇÃO RECEBIDA</span><h2>Obrigado pelo contato.</h2><p>Seu briefing foi registrado. A equipe comercial do PCH News poderá entrar em contato pelos dados informados.</p><Link className="gold-button" href="/">Voltar ao PCH News</Link></div>:<form onSubmit={submit}><div className="public-form-heading"><span className="public-kicker">FALE COM O COMERCIAL</span><h2>Vamos montar sua campanha</h2><p>Preencha em poucos passos. <strong>Não há cobrança automática.</strong> Primeiro recebemos seu briefing; depois a equipe comercial envia a proposta.</p></div>
<div className="form-section-block"><div className="form-section-title"><span>01</span><div><strong>Seus dados</strong><small>Como podemos falar com você?</small></div></div><div className="public-form-two"><label>Empresa / marca *<input required value={form.business} onChange={e=>update("business",e.target.value)} placeholder="Nome da empresa ou marca" /></label><label>Responsável *<input required value={form.contactName} onChange={e=>update("contactName",e.target.value)} placeholder="Seu nome" /></label></div><div className="public-form-two"><label>E-mail *<input required type="email" value={form.email} onChange={e=>update("email",e.target.value)} placeholder="voce@empresa.com.br" /></label><label>WhatsApp / telefone *<input required value={form.phone} onChange={e=>update("phone",e.target.value)} placeholder="(00) 00000-0000" /></label></div><div className="public-form-two"><label>Cidade / UF<input value={form.city} onChange={e=>update("city",e.target.value)} placeholder="Ex.: Osasco / SP" /></label><label>Site / redes sociais<input value={form.website} onChange={e=>update("website",e.target.value)} placeholder="https://..." /></label></div></div>
<div className="form-section-block"><div className="form-section-title"><span>02</span><div><strong>Sua campanha</strong><small>Defina o que você quer divulgar.</small></div></div><div className="public-form-two"><label>Tipo de divulgação<select value={form.adType} onChange={e=>update("adType",e.target.value)}>{formats.map(f=><option key={f}>{f}</option>)}</select></label><label>Período desejado<input value={form.period} onChange={e=>update("period",e.target.value)} placeholder="Ex.: outubro / 30 dias" /></label></div><div className="public-form-two"><label>Como prefere pagar? *<select value={form.payment} onChange={e=>update("payment",e.target.value)}>{payments.map(p=><option key={p}>{p}</option>)}</select><small className="field-note">O pagamento só acontece depois que você aprovar a proposta.</small></label><label>Faixa de investimento <span className="optional-label">opcional</span><input value={form.budget} onChange={e=>update("budget",e.target.value)} placeholder="Ex.: até R$ 1.000" /></label></div></div>
<div className="form-section-block"><div className="form-section-title"><span>03</span><div><strong>Arte e destino</strong><small>Você já tem a peça ou precisa de criação?</small></div></div><label>Como será a arte da campanha? *<select value={form.creativeNeed} onChange={e=>updateCreativeNeed(e.target.value)}><option value="no_artwork_yet">Ainda não tenho a arte</option><option value="client_artwork">Vou enviar minha própria arte</option><option value="pch_creation">Quero que o PCH News crie a arte</option></select><small className="field-note">A escolha ajuda a equipe a preparar a proposta corretamente.</small></label><div className="banner-upload-box"><span><strong>Logo / arte da campanha</strong></span><span>Opcional · JPG, PNG, WebP ou GIF · até 5 MB</span><label className="secondary-cta banner-upload-button"><Upload size={15}/>{assetUploading?"Enviando…":"Enviar arquivo"}<input type="file" accept="image/png,image/jpeg,image/webp,image/gif" onChange={e=>{const file=e.target.files?.[0];if(file)void uploadCreative(file);e.currentTarget.value="";}} disabled={assetUploading} hidden/></label>{form.creativeUrl&&<><img className="banner-art-preview" src={form.creativeUrl} alt="Arte enviada"/><button type="button" className="banner-clear-button" onClick={()=>update("creativeUrl","")}><X size={14}/> Remover arquivo</button></>}</div><label>Link de destino do anúncio <span className="optional-label">opcional</span><input type="url" value={form.destinationUrl} onChange={e=>update("destinationUrl",e.target.value)} placeholder="https://site.com.br/sua-campanha"/><small className="field-note">Pode ser site, página de vendas, WhatsApp ou download.</small></label></div>
<div className="form-section-block"><div className="form-section-title"><span>04</span><div><strong>Conte sua ideia</strong><small>Quanto melhor o briefing, melhor podemos orientar você.</small></div></div><label>Briefing / mensagem *<textarea required minLength={10} rows={6} value={form.message} onChange={e=>update("message",e.target.value)} placeholder="O que você quer divulgar? Qual é o objetivo da campanha? Há alguma data, público ou informação importante?" /></label></div><label className="consent-check"><input required type="checkbox" checked={form.consent} onChange={e=>update("consent",e.target.checked)}/><span>Autorizo o PCH News a utilizar estes dados para responder à minha solicitação comercial.</span></label>{create.isError&&<div className="form-error">{create.error.message||"Não foi possível enviar agora. Tente novamente."}</div>}<button className="gold-button" type="submit" disabled={create.isPending}><Send size={16}/>{create.isPending?"Enviando…":"Enviar solicitação"}</button></form>}</div>
      </section>
    </main><PublicFooter/>
  </div>;
}
