import { and, desc, eq, gt, isNull, sql } from "drizzle-orm";
import { drizzle } from "drizzle-orm/mysql2";
import { AdRequest, Article, ArticleAudit, ColumnistInvite, ColumnistProfile, Comment, InsertUser, adRequests, articleAudit, articles, columnistInvites, columnistProfiles, comments, users, viewEvents, editorialAgentRuns } from "../drizzle/schema";
import { ENV } from "./_core/env";
let _db: ReturnType<typeof drizzle> | null = null;
export async function getDb() { if (!_db && process.env.DATABASE_URL) { try { _db = drizzle(process.env.DATABASE_URL); } catch (error) { console.warn("[Database] Failed to connect:", error); _db = null; } } return _db; }
export async function upsertUser(user: InsertUser): Promise<void> { if (!user.openId) throw new Error("User openId is required for upsert"); const db = await getDb(); if (!db) return; const values: InsertUser = { openId: user.openId }; const updateSet: Record<string, unknown> = {}; for (const field of ["name", "email", "loginMethod"] as const) if (user[field] !== undefined) { values[field] = user[field] ?? null; updateSet[field] = user[field] ?? null; } if (user.lastSignedIn !== undefined) { values.lastSignedIn = user.lastSignedIn; updateSet.lastSignedIn = user.lastSignedIn; } if (user.role !== undefined) { values.role = user.role; updateSet.role = user.role; } else if (user.openId === ENV.ownerOpenId) { values.role = "admin"; updateSet.role = "admin"; } values.lastSignedIn ??= new Date(); if (!Object.keys(updateSet).length) updateSet.lastSignedIn = new Date(); await db.insert(users).values(values).onDuplicateKeyUpdate({ set: updateSet }); }
export async function getUserByOpenId(openId: string) { const db = await getDb(); if (!db) return undefined; const result = await db.select().from(users).where(eq(users.openId, openId)).limit(1); return result[0]; }
export async function getEditorialSnapshot() { const db = await getDb(); if (!db) return { articles: [], comments: [], profiles: [], adRequests: [] }; const [articleRows, commentRows, profileRows, adRows] = await Promise.all([db.select().from(articles), db.select().from(comments), db.select().from(columnistProfiles), db.select().from(adRequests)]); return { articles: articleRows, comments: commentRows, profiles: profileRows, adRequests: adRows }; }
export async function recordArticleView(articleId: string, visitorId: string) { const db = await getDb(); if (!db) return { counted: false, views: 0 }; const cutoff = Date.now() - 30 * 60 * 1000; const recent = await db.select({ id: viewEvents.id }).from(viewEvents).where(and(eq(viewEvents.articleId, articleId), eq(viewEvents.visitorId, visitorId), gt(viewEvents.viewedAtMs, cutoff))).limit(1); if (recent.length) { const row = await db.select({ views: articles.views }).from(articles).where(eq(articles.id, articleId)).limit(1); return { counted: false, views: row[0]?.views ?? 0 }; } await db.insert(viewEvents).values({ id: `view-${Date.now()}-${Math.random().toString(36).slice(2, 8)}`, articleId, visitorId, viewedAtMs: Date.now() }); await db.update(articles).set({ views: sql`${articles.views} + 1` }).where(eq(articles.id, articleId)); const row = await db.select({ views: articles.views }).from(articles).where(eq(articles.id, articleId)).limit(1); return { counted: true, views: row[0]?.views ?? 0 }; }
export async function getViewAnalytics(author?: string, authorOpenId?: string, fromMs?: number, toMs?: number) { const db = await getDb(); if (!db) return { events: [], totals: [] }; const [eventRows, articleRows] = await Promise.all([db.select().from(viewEvents).orderBy(desc(viewEvents.viewedAtMs)), db.select().from(articles)]); const allowedIds = new Set(articleRows.filter((article) => (!author || article.author === author) && (!authorOpenId || article.authorOpenId === authorOpenId)).map((article) => article.id)); const events = eventRows.filter((event) => allowedIds.has(event.articleId) && (!fromMs || event.viewedAtMs >= fromMs) && (!toMs || event.viewedAtMs <= toMs)).map((event) => ({ articleId: event.articleId, viewedAtMs: event.viewedAtMs })); const totals = articleRows.filter((article) => allowedIds.has(article.id)).map((article) => ({ articleId: article.id, views: article.views })); return { events, totals }; }
export async function updateColumnistProfile(slug: string, profile: Omit<ColumnistProfile, "updatedAt">) { const db = await getDb(); if (!db) throw new Error("Database unavailable"); await db.insert(columnistProfiles).values({ ...profile, slug }).onDuplicateKeyUpdate({ set: { name: profile.name, beat: profile.beat, bio: profile.bio, photo: profile.photo, instagram: profile.instagram, facebook: profile.facebook, x: profile.x, linkedin: profile.linkedin } }); return { success: true }; }
export type EditorialSyncPayload = { articles: Array<Omit<Article, "createdAt" | "updatedAt"> & Partial<Pick<Article, "createdAt" | "updatedAt">>>; comments: Comment[]; profiles: Array<Omit<ColumnistProfile, "updatedAt"> & Partial<Pick<ColumnistProfile, "updatedAt">>>; adRequests: AdRequest[] };
export async function syncEditorial(payload: EditorialSyncPayload) { const db = await getDb(); if (!db) throw new Error("Database unavailable"); for (const article of payload.articles) await db.insert(articles).values(article).onDuplicateKeyUpdate({ set: { title: article.title, category: article.category, author: article.author, authorOpenId: article.authorOpenId, summary: article.summary, date: article.date, updated: article.updated, status: article.status, views: article.views, image: article.image, bodyHtml: article.bodyHtml, scheduledAt: article.scheduledAt, tags: article.tags, youtubeUrl: article.youtubeUrl ?? null, socialLinks: article.socialLinks ?? null } }); for (const comment of payload.comments) await db.insert(comments).values(comment).onDuplicateKeyUpdate({ set: { articleId: comment.articleId, name: comment.name, text: comment.text, createdAtMs: comment.createdAtMs, status: comment.status, reply: comment.reply, repliedBy: comment.repliedBy, repliedAtMs: comment.repliedAtMs } }); for (const profile of payload.profiles) await db.insert(columnistProfiles).values(profile).onDuplicateKeyUpdate({ set: { name: profile.name, beat: profile.beat, bio: profile.bio, photo: profile.photo, instagram: profile.instagram, facebook: profile.facebook, x: profile.x, linkedin: profile.linkedin } }); for (const ad of payload.adRequests) await db.insert(adRequests).values(ad).onDuplicateKeyUpdate({ set: { business: ad.business, contact: ad.contact, packageName: ad.packageName, message: ad.message, status: ad.status, createdAtMs: ad.createdAtMs } }); return { success: true }; }
export async function createInvite(invite: ColumnistInvite) { const db = await getDb(); if (!db) throw new Error("Database unavailable"); await db.insert(columnistInvites).values(invite); return invite; }
export async function listInvites() { const db = await getDb(); if (!db) return []; return db.select().from(columnistInvites).orderBy(desc(columnistInvites.createdAtMs)); }
export async function findInvite(tokenHash: string) { const db = await getDb(); if (!db) return undefined; const result = await db.select().from(columnistInvites).where(and(eq(columnistInvites.tokenHash, tokenHash), isNull(columnistInvites.acceptedAtMs), isNull(columnistInvites.revokedAtMs))).limit(1); return result[0]; }
export async function acceptInvite(id: string) { const db = await getDb(); if (!db) throw new Error("Database unavailable"); await db.update(columnistInvites).set({ acceptedAtMs: Date.now() }).where(eq(columnistInvites.id, id)); }

export async function revokeInvite(id: string) { const db = await getDb(); if (!db) throw new Error("Database unavailable"); await db.update(columnistInvites).set({ revokedAtMs: Date.now() }).where(eq(columnistInvites.id, id)); return { success: true }; }
export async function renewInvite(id: string, tokenHash: string, expiresAtMs: number) { const db = await getDb(); if (!db) throw new Error("Database unavailable"); const result = await db.select().from(columnistInvites).where(eq(columnistInvites.id, id)).limit(1); const invite = result[0]; if (!invite || invite.acceptedAtMs || invite.revokedAtMs) return undefined; await db.update(columnistInvites).set({ tokenHash, expiresAtMs, createdAtMs: Date.now() }).where(eq(columnistInvites.id, id)); return { ...invite, tokenHash, expiresAtMs, createdAtMs: Date.now() }; }
export async function recordArticleAudit(entry: Omit<ArticleAudit, "createdAtMs">) { const db = await getDb(); if (!db) throw new Error("Database unavailable"); await db.insert(articleAudit).values({ ...entry, createdAtMs: Date.now() }); return { success: true }; }
export async function listArticleAudit(articleId?: string) { const db = await getDb(); if (!db) return []; const query = db.select({ id: articleAudit.id, articleId: articleAudit.articleId, articleTitle: articles.title, actorOpenId: articleAudit.actorOpenId, actorName: articleAudit.actorName, action: articleAudit.action, beforeJson: articleAudit.beforeJson, afterJson: articleAudit.afterJson, createdAtMs: articleAudit.createdAtMs }).from(articleAudit).leftJoin(articles, eq(articleAudit.articleId, articles.id)); return articleId ? query.where(eq(articleAudit.articleId, articleId)).orderBy(desc(articleAudit.createdAtMs)) : query.orderBy(desc(articleAudit.createdAtMs)); }


export async function recordEditorialAgentRun(entry: { id: string; articleId: string; agentId: string; agentName: string; status: "pass" | "review" | "block"; findingsJson: string; outputJson: string; actorOpenId: string; createdAtMs: number }) {
  const db = await getDb();
  if (!db) return { success: false };
  await db.insert(editorialAgentRuns).values(entry);
  return { success: true };
}

export async function listEditorialAgentRuns(articleId: string) {
  const db = await getDb();
  if (!db) return [];
  return db.select().from(editorialAgentRuns).where(eq(editorialAgentRuns.articleId, articleId)).orderBy(desc(editorialAgentRuns.createdAtMs)).limit(100);
}
