/* eslint-disable */
import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as NoticiaSlugRouteImport } from './routes/noticia.$slug'
import { Route as CategoriaSlugRouteImport } from './routes/categoria.$slug'
import { Route as CategoriasRouteImport } from './routes/categorias'
import { Route as ColunistasRouteImport } from './routes/colunistas'
import { Route as ColunistasSlugRouteImport } from './routes/colunistas.$slug'
import { Route as LoginRouteImport } from './routes/login'
import { Route as RobotsDottxtRouteImport } from './routes/robots[.]txt'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
const IndexRoute=IndexRouteImport.update({id:'/',path:'/',getParentRoute:()=>rootRouteImport} as any)
const AdminRoute=AdminRouteImport.update({id:'/admin',path:'/admin',getParentRoute:()=>rootRouteImport} as any)
const NoticiaSlugRoute=NoticiaSlugRouteImport.update({id:'/noticia/$slug',path:'/noticia/$slug',getParentRoute:()=>rootRouteImport} as any)
const CategoriaSlugRoute=CategoriaSlugRouteImport.update({id:'/categoria/$slug',path:'/categoria/$slug',getParentRoute:()=>rootRouteImport} as any)
const CategoriasRoute=CategoriasRouteImport.update({id:'/categorias',path:'/categorias',getParentRoute:()=>rootRouteImport} as any)
const ColunistasRoute=ColunistasRouteImport.update({id:'/colunistas',path:'/colunistas',getParentRoute:()=>rootRouteImport} as any)
const ColunistasSlugRoute=ColunistasSlugRouteImport.update({id:'/colunistas/$slug',path:'/colunistas/$slug',getParentRoute:()=>rootRouteImport} as any)
const LoginRoute=LoginRouteImport.update({id:'/login',path:'/login',getParentRoute:()=>rootRouteImport} as any)
const RobotsDottxtRoute=RobotsDottxtRouteImport.update({id:'/robots.txt',path:'/robots.txt',getParentRoute:()=>rootRouteImport} as any)
const SitemapDotxmlRoute=SitemapDotxmlRouteImport.update({id:'/sitemap.xml',path:'/sitemap.xml',getParentRoute:()=>rootRouteImport} as any)
export interface FileRoutesByFullPath{'/':typeof IndexRoute;'/admin':typeof AdminRoute;'/noticia/$slug':typeof NoticiaSlugRoute;'/categoria/$slug':typeof CategoriaSlugRoute;'/categorias':typeof CategoriasRoute;'/colunistas':typeof ColunistasRoute;'/colunistas/$slug':typeof ColunistasSlugRoute;'/login':typeof LoginRoute;'/robots.txt':typeof RobotsDottxtRoute;'/sitemap.xml':typeof SitemapDotxmlRoute}
export interface FileRoutesByTo{ '/':typeof IndexRoute;'/admin':typeof AdminRoute;'/noticia/$slug':typeof NoticiaSlugRoute;'/categoria/$slug':typeof CategoriaSlugRoute;'/categorias':typeof CategoriasRoute;'/colunistas':typeof ColunistasRoute;'/colunistas/$slug':typeof ColunistasSlugRoute;'/login':typeof LoginRoute;'/robots.txt':typeof RobotsDottxtRoute;'/sitemap.xml':typeof SitemapDotxmlRoute}
export interface FileRouteTypes{fileRoutesByFullPath:FileRoutesByFullPath;fullPaths:'/'|'/admin'|'/noticia/$slug'|'/categoria/$slug'|'/categorias'|'/colunistas'|'/colunistas/$slug'|'/login'|'/robots.txt'|'/sitemap.xml';fileRoutesByTo:FileRoutesByTo;to:'/'|'/admin'|'/noticia/$slug'|'/categoria/$slug'|'/categorias'|'/colunistas'|'/colunistas/$slug'|'/login'|'/robots.txt'|'/sitemap.xml';id:'__root__'|'/'|'/admin'|'/noticia/$slug'|'/categoria/$slug'|'/categorias'|'/colunistas'|'/colunistas/$slug'|'/login'|'/robots.txt'|'/sitemap.xml';fileRoutesById:FileRoutesById}
export interface FileRoutesById{__root__:typeof rootRouteImport;'/':typeof IndexRoute;'/admin':typeof AdminRoute;'/noticia/$slug':typeof NoticiaSlugRoute;'/categoria/$slug':typeof CategoriaSlugRoute;'/categorias':typeof CategoriasRoute;'/colunistas':typeof ColunistasRoute;'/colunistas/$slug':typeof ColunistasSlugRoute;'/login':typeof LoginRoute;'/robots.txt':typeof RobotsDottxtRoute;'/sitemap.xml':typeof SitemapDotxmlRoute}
export interface RootRouteChildren{IndexRoute:typeof IndexRoute;AdminRoute:typeof AdminRoute;NoticiaSlugRoute:typeof NoticiaSlugRoute;CategoriaSlugRoute:typeof CategoriaSlugRoute;CategoriasRoute:typeof CategoriasRoute;ColunistasRoute:typeof ColunistasRoute;ColunistasSlugRoute:typeof ColunistasSlugRoute;LoginRoute:typeof LoginRoute;RobotsDottxtRoute:typeof RobotsDottxtRoute;SitemapDotxmlRoute:typeof SitemapDotxmlRoute}
declare module '@tanstack/react-router'{interface FileRoutesByPath{'/':{id:'/';path:'/';fullPath:'/';preLoaderRoute:typeof IndexRouteImport;parentRoute:typeof rootRouteImport};'/admin':{id:'/admin';path:'/admin';fullPath:'/admin';preLoaderRoute:typeof AdminRouteImport;parentRoute:typeof rootRouteImport};'/noticia/$slug':{id:'/noticia/$slug';path:'/noticia/$slug';fullPath:'/noticia/$slug';preLoaderRoute:typeof NoticiaSlugRouteImport;parentRoute:typeof rootRouteImport};'/categoria/$slug':{id:'/categoria/$slug';path:'/categoria/$slug';fullPath:'/categoria/$slug';preLoaderRoute:typeof CategoriaSlugRouteImport;parentRoute:typeof rootRouteImport};'/categorias':{id:'/categorias';path:'/categorias';fullPath:'/categorias';preLoaderRoute:typeof CategoriasRouteImport;parentRoute:typeof rootRouteImport};'/colunistas':{id:'/colunistas';path:'/colunistas';fullPath:'/colunistas';preLoaderRoute:typeof ColunistasRouteImport;parentRoute:typeof rootRouteImport};'/colunistas/$slug':{id:'/colunistas/$slug';path:'/colunistas/$slug';fullPath:'/colunistas/$slug';preLoaderRoute:typeof ColunistasSlugRouteImport;parentRoute:typeof rootRouteImport};'/login':{id:'/login';path:'/login';fullPath:'/login';preLoaderRoute:typeof LoginRouteImport;parentRoute:typeof rootRouteImport};'/robots.txt':{id:'/robots.txt';path:'/robots.txt';fullPath:'/robots.txt';preLoaderRoute:typeof RobotsDottxtRouteImport;parentRoute:typeof rootRouteImport};'/sitemap.xml':{id:'/sitemap.xml';path:'/sitemap.xml';fullPath:'/sitemap.xml';preLoaderRoute:typeof SitemapDotxmlRouteImport;parentRoute:typeof rootRouteImport}}}
const rootRouteChildren:RootRouteChildren={IndexRoute,AdminRoute,NoticiaSlugRoute,CategoriaSlugRoute,CategoriasRoute,ColunistasRoute,ColunistasSlugRoute,LoginRoute,RobotsDottxtRoute,SitemapDotxmlRoute}
export const routeTree=rootRouteImport._addFileChildren(rootRouteChildren)._addFileTypes<FileRouteTypes>()
import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start'{interface Register{ssr:true;router:Awaited<ReturnType<typeof getRouter>>;config:Awaited<ReturnType<typeof startInstance.getOptions>>}}