-- PCH News / Supabase foundation
-- Run this in Supabase SQL Editor before using the migrated auth/storage layer.
create table if not exists public.users (
  id bigint generated by default as identity primary key,
  "openId" text not null unique,
  name text,
  email text,
  "loginMethod" text,
  role text not null default 'user' check (role in ('user','admin','columnist')),
  "createdAt" timestamptz not null default now(),
  "updatedAt" timestamptz not null default now(),
  "lastSignedIn" timestamptz not null default now()
);

-- Compatibility helper used by the early RLS migrations.
-- Later hardening moves authorization checks to private.is_admin().
create or replace function public.is_admin()
returns boolean
language sql
stable
security definer
set search_path = public
as $
  select exists (
    select 1
    from public.users
    where "openId" = auth.uid()::text
      and role = 'admin'
  );
$;

revoke all on function public.is_admin() from public;

create table if not exists public.articles (
  id text primary key,
  title text not null,
  category text not null,
  author text not null,
  "authorOpenId" text,
  summary text not null,
  date text not null,
  updated text not null,
  status text not null default 'draft' check (status in ('published','draft','scheduled','archived')),
  views integer not null default 0,
  image text not null,
  "bodyHtml" text not null,
  "scheduledAt" bigint,
  tags text not null,
  "createdAt" timestamptz not null default now(),
  "updatedAt" timestamptz not null default now()
);

create table if not exists public."viewEvents" (
  id text primary key,
  "articleId" text not null,
  "visitorId" text not null,
  "viewedAtMs" bigint not null
);

create table if not exists public.comments (
  id text primary key,
  "articleId" text not null,
  name text not null,
  text text not null,
  "createdAtMs" bigint not null,
  status text not null default 'pending' check (status in ('pending','approved','rejected')),
  reply text,
  "repliedBy" text,
  "repliedAtMs" bigint
);

create table if not exists public."columnistProfiles" (
  slug text primary key,
  name text not null,
  beat text not null,
  bio text not null,
  photo text not null,
  instagram text not null,
  facebook text not null,
  x text not null,
  linkedin text not null,
  "updatedAt" timestamptz not null default now()
);

create table if not exists public."adRequests" (
  id text primary key,
  business text not null,
  contact text not null,
  "packageName" text not null,
  message text not null,
  status text not null default 'received' check (status in ('received','reviewing','approved')),
  "createdAtMs" bigint not null
);

create table if not exists public."columnistInvites" (
  id text primary key,
  email text not null,
  name text not null,
  "tokenHash" text not null unique,
  "expiresAtMs" bigint not null,
  "createdAtMs" bigint not null,
  "acceptedAtMs" bigint
);

create index if not exists "viewEvents_articleId_viewedAtMs_idx"
  on public."viewEvents" ("articleId", "viewedAtMs");

alter table public.users enable row level security;
alter table public.articles enable row level security;
alter table public."viewEvents" enable row level security;
alter table public.comments enable row level security;
alter table public."columnistProfiles" enable row level security;
alter table public."adRequests" enable row level security;
alter table public."columnistInvites" enable row level security;

-- The current Express API uses the Supabase service-role key server-side.
-- No client-side table policies are opened here yet; they will be added when
-- the remaining MySQL/Drizzle data layer is switched to Supabase/Postgres.

insert into storage.buckets (id, name, public)
values ('media', 'media', true)
on conflict (id) do update set public = true;
