name: PCH News Dependency Review

permissions:
  contents: read

on:
  pull_request:
    branches: [main]

jobs:
  dependency-review:
    runs-on: ubuntu-latest
    steps:
      - name: Dependency review
        uses: actions/dependency-review-action@v4
